### ISSUE TITLE
timestamp and timedelta columns are not displayed.

### ISSUE THREAD

**Issue by ghost** [buckaroo-data/buckaroo#132]
<img width="548" alt="15" src="https://github.com/paddymul/buckaroo/assets/79505893/a0ef2a00-6ee6-4fb2-bbbc-beb8e0425555">
<img width="585" alt="16" src="https://github.com/paddymul/buckaroo/assets/79505893/a09b736e-bff6-42bf-8017-0430ada5baa5">

**Comment by paddymul** [comment]
<img width="649" alt="Screen Shot 2023-11-16 at 4 05 01 PM" src="https://github.com/paddymul/buckaroo/assets/40453/9e209063-e895-48a8-ba12-801dacdf8753">
This is better with 0.4.6 

in the itables dataframe, the `timestamp` column becomes an object column... I think because of the mixing of TZ Aware and TZ Unaware timestamps.  That's why `None` shows up.  Time Delta is serialized in some special way, but it has a proper `dtype`.  At some point when there is user demand, I will build a timedelta formatter.  For now, something displays, and that is enough
