### ISSUE TITLE
Table sizing (set the height)

### ISSUE THREAD

**Issue by sebtechni** [buckaroo-data/buckaroo#196]
### Checks

- [X] I have checked that this enhancement has not already been requested

### How would you categorize this request.  You can select multiple if not sure

Display (is this related to visual display of a value)

### Enhancement Description

Unless I miss the option somewhere, it would be good to be able to set the height of the table.

### Prior Art

It can be done with ipydatagrid.
![image](https://github.com/paddymul/buckaroo/assets/68927207/bdf172f2-82ca-4898-8a57-4921089810b7)

**Comment by paddymul** [comment]
Thanks for the request!  That isn't supported at this point.  I should be getting to a bunch of JS issues shortly I will include this in that next set of bugs.

A couple of statements and questions, please provide feedback:
Setting heights in pixels should be fairly straight forward.
I don't know how to set a height in rows.  I would like to do that for small dataframes
What is a good sensible default for height?  I would think half of the browser height.

What other thoughts do you have around sizing or other features compared to ipydatagrid?

**Comment by sebtechni** [comment]
Good questions.

> "Setting heights in pixels should be fairly straight forward" 

-> Nice, that's the main idea

> "I would think half of the browser height"

 -> Sounds good to me.

What would be better is to dynamically resize the table like a text box; like so : ![image](https://github.com/paddymul/buckaroo/assets/68927207/891c9ca4-538f-4e43-a6fd-f88625e82e2c)

Also, regarding sizing, you can also change the column width in ipydatagrid.

**Comment by paddymul** [comment]
@sebtechni this was fixed in #250 released at 0.6.5

You can control widget height with  
`BuckarooWidget(df, component_config={'height_fraction':1.2}`
you can also control widget height with
`BuckarooWidget(df,  extra_grid_config={'rowHeight':305})` which will create 305 pixel high rows

Also Buckaroo shrinks when there are less than 10 rows displayed between the main dataframe and summary stats.

Can you give it a try? and let me know your thoughts.
