### ISSUE TITLE
Nearly-constant column with outliers fails to display

### ISSUE THREAD

**Issue by awray3** [buckaroo-data/buckaroo#264]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/paddymul/buckaroo) of Buckaroo.

### What type of jupyter notebook were you using (VSCode notebook, google colab, Jupyter Lab, Jupyter notebook).  Select multiple if you can reproduce this in multiple environments.  If other, please add to description.

VS Code

### Reproducible example

```python
import pandas as pd
import buckaroo

# one column that contains mostly 1s and a couple of larger values
data = [1] * 400 + [10, 20, 30, 40, 50]

df = pd.DataFrame({'data': data})
df
```

### Issue description

When I run that example the buckaroo output shows up correctly but just says "no rows to show". Furthermore, the following message pops up:

```
Histogram.summary(placeholder['data'], pd.Series({'value_counts': pd.Series(), 'nan_per': 0.0, 'is_numeric': True, 'length': 405, 'min': 1, 'max': 50, }), placeholder['data']) # 'low_tail'
```

### Expected behavior

I expect it to show up like a regular column. If you change the data to `data = [1] * 400 + [10, 20, 30, 40]` with one fewer outlier, the column appears correctly. It also appears correctly if you lower the number of repeated 1's, say from 400 down to 300.

### Installed versions

<details>

```
Selected Jupyter core packages...
executing in unknown 
buckaroo         : 0.6.10
jupyterlab       : not installed
notebook         : not installed
ipywidgets       : 8.1.2
traitlets        : 5.14.2
jupyter_core     : 5.7.2
pandas           : 2.2.1
numpy            : 1.26.4
IPython          : 8.22.2
ipykernel        : 6.29.3
jupyter_client   : 8.6.1
jupyter_server   : not installed
nbclient         : not installed
nbconvert        : not installed
nbformat         : not installed
qtconsole        : not installed
buckaroo         : [/Users/andrew/code/tmp/buckaroo-example/.pixi/envs/default/lib/python3.12/site-packages/buckaroo/__init__.py](https://file+.vscode-resource.vscode-cdn.net/Users/andrew/code/tmp/buckaroo-example/.pixi/envs/default/lib/python3.12/site-packages/buckaroo/__init__.py)
jupyterlab       : not installed
notebook         : not installed
ipywidgets       : [/Users/andrew/code/tmp/buckaroo-example/.pixi/envs/default/lib/python3.12/site-packages/ipywidgets/__init__.py](https://file+.vscode-resource.vscode-cdn.net/Users/andrew/code/tmp/buckaroo-example/.pixi/envs/default/lib/python3.12/site-packages/ipywidgets/__init__.py)
traitlets        : [/Users/andrew/code/tmp/buckaroo-example/.pixi/envs/default/lib/python3.12/site-packages/traitlets/__init__.py](https://file+.vscode-resource.vscode-cdn.net/Users/andrew/code/tmp/buckaroo-example/.pixi/envs/default/lib/python3.12/site-packages/traitlets/__init__.py)
jupyter_core     : [/Users/andrew/code/tmp/buckaroo-example/.pixi/envs/default/lib/python3.12/site-packages/jupyter_core/__init__.py](https://file+.vscode-resource.vscode-cdn.net/Users/andrew/code/tmp/buckaroo-example/.pixi/envs/default/lib/python3.12/site-packages/jupyter_core/__init__.py)
pandas           : [/Users/andrew/code/tmp/buckaroo-example/.pixi/envs/default/lib/python3.12/site-packages/pandas/__init__.py](https://file+.vscode-resource.vscode-cdn.net/Users/andrew/code/tmp/buckaroo-example/.pixi/envs/default/lib/python3.12/site-packages/pandas/__init__.py)
numpy            : [/Users/andrew/code/tmp/buckaroo-example/.pixi/envs/default/lib/python3.12/site-packages/numpy/__init__.py](https://file+.vscode-resource.vscode-cdn.net/Users/andrew/code/tmp/buckaroo-example/.pixi/envs/default/lib/python3.12/site-packages/numpy/__init__.py)
IPython          : [/Users/andrew/code/tmp/buckaroo-example/.pixi/envs/default/lib/python3.12/site-packages/IPython/__init__.py](https://file+.vscode-resource.vscode-cdn.net/Users/andrew/code/tmp/buckaroo-example/.pixi/envs/default/lib/python3.12/site-packages/IPython/__init__.py)
ipykernel        : [/Users/andrew/code/tmp/buckaroo-example/.pixi/envs/default/lib/python3.12/site-packages/ipykernel/__init__.py](https://file+.vscode-resource.vscode-cdn.net/Users/andrew/code/tmp/buckaroo-example/.pixi/envs/default/lib/python3.12/site-packages/ipykernel/__init__.py)
jupyter_client   : [/Users/andrew/code/tmp/buckaroo-example/.pixi/envs/default/lib/python3.12/site-packages/jupyter_client/__init__.py](https://file+.vscode-resource.vscode-cdn.net/Users/andrew/code/tmp/buckaroo-example/.pixi/envs/default/lib/python3.12/site-packages/jupyter_client/__init__.py)
jupyter_server   : not installed
nbclient         : not installed
nbconvert        : not installed
nbformat         : not installed
qtconsole        : not installed
```
</details>

**Comment by paddymul** [comment]
Thanks for the bug report!  I narrowed down the code that's causing the bug.  I'm trying to figure out the best way to handle this case.

I should have a fix out tomorrow or the next day.

**Comment by paddymul** [comment]
Buckaroo has two types of histograms, numeric and categorical.

Buckaroo's numeric histograms, show the histogram between the 1st and 99th percentile by default.  for your sample dataset the first percentile is `1.0` and the 99th is `9.63`.  that leaves an empty middle of the histogram, which causes an error.

I limit the numerical histogram to the 1st and 99th because otherwise the outlier values effectively force each bin to be too wide, and you end up with a single dominant bin and no resolution.

Categorical histograms are used for numeric columns when there are less than 5 distinct values.  My reasoning being that when there are a small number of distinct values, you are dealing with some type of flag field that is encoded numerically, not an actual distribution of values that fit a histogram usecase.

Fixing this particular error is easy, I can just force the histogram to be a categorical histogram when there is no `meat` between the 1st and 99th percentile.  

I'm not sure what a generic histogram should do in this case.  I designed histograms in buckaroo to use that space on the screen to give a first glance overview of the distribution of values for the column... Not as a complex completely reasoned chart.  That's my opinion.

The great thing about buckaroo though, is that it's made so you can insert your own opinions into the analysis.  What do you think the histogram should display in this case?  I am happy to work with you to design your own ideal histogram and show you how to integrate it into buckaroo.
