### ISSUE TITLE
Combination of Integers and strings

### ISSUE THREAD

**Issue by ghost** [buckaroo-data/buckaroo#77]
"all Integers with single string " - string is taken as NA
"all Integers with more than one string " - throwing mean not in index error.
"single Integer with single string " - throwing mean not in index error.
"all strings with single integer " - throwing mean not in index error.
"two strings with single integer" - displaying 
<img width="212" alt="19" src="https://github.com/paddymul/buckaroo/assets/79505893/cee55202-675d-493b-8b45-ca91a057aef9">
<img width="331" alt="20" src="https://github.com/paddymul/buckaroo/assets/79505893/36879418-55d5-41b9-b8ae-cf1e8e54986b">

**Comment by paddymul** [comment]
`Mean not in index` was just fixed with the most recent release https://github.com/paddymul/buckaroo/issues/52.
Try upgrading with `pip install -U buckaroo`, restart jupyter lab

All integers with single string... Buckaroo autoClean is converting the column to integers, discarding values that aren't integers.

This behavior though confusing is as designed.  There are other issues detailing each bug here.  I will add another issue about another approach to autocleaning afforadnaces to make the autocleaning functionality more clear. #79

**Comment by ghost** [comment]
<img width="461" alt="20" src="https://github.com/paddymul/buckaroo/assets/79505893/44730f4f-d372-4dbe-89eb-9daeae92fdb0">


import pandas as pd
df1 = pd.DataFrame(
    dict(Names=[1,2,'one','two',3]))
df1

import pandas as pd
df1 = pd.DataFrame(
    dict(Names=[1,2,'one','two',3,4,'six']))
df1
The following codes shows NA for me.
