### ISSUE TITLE
Multi Indexes don't display

### ISSUE THREAD

**Issue by paddymul** [buckaroo-data/buckaroo#89]
The following code doesn't display an index
```
pd.DataFrame(
    {'a':[10,20,30,40]}, 
    index=pd.MultiIndex.from_tuples(
        [(True, 'foo'), (True, 'bar'), 
         (False, 'foo'), (False, 'bar')], 
        names=['is_weekend', 'str_qualifier']))
```
<img width="512" alt="Screen Shot 2023-10-30 at 6 00 34 PM" src="https://github.com/paddymul/buckaroo/assets/40453/f82ba0a7-f7d6-4aac-9a4a-3e7096f5852e">

This is frequently a problem with grouped DataFrames

**Comment by paddymul** [comment]
I eventually want a nested index.  In the meantime, just converting multi-index to objects is a nice stopgap
```
pd.DataFrame({'a':[10,20,30]}, index=[(True, True), (True, False), (False,False)])
```
<img width="618" alt="Screen Shot 2023-10-30 at 6 23 03 PM" src="https://github.com/paddymul/buckaroo/assets/40453/cc2f63a1-cd5a-4f44-ba14-ec6244b6de1a">

**Comment by ghost** [comment]
For me the following code works for dataframe but displaying blank for the Buckaroowidget.
<img width="491" alt="1" src="https://github.com/paddymul/buckaroo/assets/79505893/51384629-ed17-4ee6-bffb-626cfffd6c8b">
<img width="503" alt="2" src="https://github.com/paddymul/buckaroo/assets/79505893/4d903931-73bb-4554-9388-261d84ef9f14">
Buckaroowidget with autotype=False displays all columns.

**Comment by ghost** [comment]
"index" default index name is not changable.
<img width="420" alt="19" src="https://github.com/paddymul/buckaroo/assets/79505893/f2fbc2bd-69fa-46c1-aa80-f7d833c238ca">
 
<img width="589" alt="21" src="https://github.com/paddymul/buckaroo/assets/79505893/b5439c37-2550-4f20-8264-d66ff8d0e94d">

  Multi indexes shows blank because of that.

<img width="480" alt="22" src="https://github.com/paddymul/buckaroo/assets/79505893/20812196-67e4-4d7c-b36f-2dd48d58355c">

<img width="585" alt="23" src="https://github.com/paddymul/buckaroo/assets/79505893/0db4dcf0-4533-4268-b258-398c76397134">
